name: Build and Publish

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [21]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM Install
        run: |
          npm install

      - name: Package extension
        if: success()
        run: |
          npm install -g vsce
          vsce package

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 21
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: NPM Install
        run: npm install

      - name: Publish extension
        run: |
          npm install -g vsce
          vsce publish -p ${{ secrets.VSCE_TOKEN }}
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        continue-on-error: true
